version: "3"
services:
  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./template.env:/app/.env
